###

POST http://127.0.0.1:8000/login/
Content-Type: application/json

{"username": "sena5", "password":"Pass1234!"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "abdullah", "password":"Pass1234!"}

###
POST http://127.0.0.1:8000/sena4/follow
Content-Type: application/json


###
POST http://127.0.0.1:8000/tweet/tweet/
Content-Type: application/json

{"tweet":"oldu mu deniyorz"}

###

GET http://127.0.0.1:8000/tweet/tweet
Content-Type: application/json


###

POST http://127.0.0.1:8000/tweet/retweet
Content-Type: application/json

{"tweet_user":"sena4","tweet_text":"retweet yaptık"}

###

GET http://127.0.0.1:8000/tweet/tweet/my_profile_timeline_list
Content-Type: application/json


###

GET http://127.0.0.1:8000/tweet/tweet/6/user_profile_timeline_list
Content-Type: application/json


###



