# Generated by Django 4.2.2 on 2023-09-19 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HashTags', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=280)),
                ('time', models.CharField(default='09/19/2023 10:26:22 AM', max_length=50)),
                ('hashtags', models.ManyToManyField(related_name='hahstag', to='HashTags.hashtags')),
                ('likes', models.ManyToManyField(related_name='liked_users', to='Users.users')),
                ('replies', models.ManyToManyField(related_name='reply_text', to='Tweets.tweets')),
                ('retweets', models.ManyToManyField(related_name='retweeted_users', to='Users.users')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
    ]
