# Generated by Django 4.2.5 on 2023-09-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0004_alter_tweets_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='time',
            field=models.CharField(default='09/27/2023 11:48:33 AM', max_length=50),
        ),
    ]
