# Generated by Django 4.2.5 on 2023-09-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0005_alter_tweets_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='time',
            field=models.CharField(default='09/28/2023 06:00:04 PM', max_length=50),
        ),
    ]
