# Generated by Django 4.2.5 on 2023-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_users', to='Users.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_users', to='Users.users'),
        ),
    ]
