# Generated by Django 4.2.5 on 2023-09-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_followers_alter_users_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
