# Generated by Django 4.2.5 on 2023-09-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='follow_request', to='Users.users'),
        ),
    ]
